//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppDatabaseFistAirportH3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Router
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Router()
        {
            this.Airlines = new HashSet<Airline>();
        }
    
        public int RouteId { get; set; }
        public string HomeIATACode { get; set; }
        public string DestinationIATACode { get; set; }
        public Nullable<int> RouteOwnerId { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Airline> Airlines { get; set; }
    }
}
